default: &default
  adapter: postgresql
  encoding: unicode
  username: projectio
  password: projectio
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: projectio_development

test:
  <<: *default
  database: projectio_test

production:
  <<: *default
  database: projectio_production
  password: <%= ENV["PROJECTIO_DATABASE_PASSWORD"] %>
