default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['PGDATABASE'] || 'projectio_db' %>
  username: <%= ENV['POSTGRES_USER'] || 'projectio' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'projectio' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['PGPORT'] || 5432 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
